version: "3"
services:
  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    ports:
      - "7000:7000"
    volumes:
      - ../cms:/var/www/statamic-site/
  fpm:
    build:
      context: ./
      dockerfile: fpm.Dockerfile
    volumes:
      - ../cms:/var/www/statamic-site/
